"""
Markdown formatter for transcription output.
"""

import os
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from ..core.interfaces import Formatter
from ..core.types import Document, ProcessingConfig, ProcessingStatus


class MarkdownFormatter(Formatter):
    """Markdown formatter for transcription output."""
    
    def __init__(self):
        """Initialize markdown formatter."""
        self.logger = logging.getLogger(__name__)
        self.templates = self._load_templates()
    
    def _load_templates(self) -> Dict[str, str]:
        """Load markdown templates."""
        return {
            'default': """# {title}

**Source:** {source_file}  
**Language:** {language}  
**Generated:** {timestamp}  
**Duration:** {duration}

---

{segments}

---

*Generated by Movie Audio Transcription Tool*""",

            'minimal': """# {title}

{segments}""",

            'detailed': """# {title}

## Metadata
- **Source File:** {source_file}
- **Language:** {language}
- **Generated:** {timestamp}
- **Duration:** {duration}
- **Segments:** {segment_count}
- **Average Confidence:** {avg_confidence}

## Transcription

{segments}

## Statistics
- Total segments: {segment_count}
- Average confidence: {avg_confidence}
- Processing time: {processing_time}

---
*Generated by Movie Audio Transcription Tool*""",

            'timeline': """# {title}

**Source:** {source_file} | **Language:** {language} | **Duration:** {duration}

---

## Timeline

{timeline_segments}

---

*Generated by Movie Audio Transcription Tool*"""
        }
    
    def format(self, document: Document, config: ProcessingConfig) -> Document:
        """
        Format transcription to markdown.
        
        Args:
            document: Document with transcription data
            config: Processing configuration
            
        Returns:
            Document with formatted output
        """
        try:
            if not hasattr(document, 'transcription_segments') or not document.transcription_segments:
                document.add_error("No transcription data available for formatting")
                return document
            
            # Get template
            template_name = config.config.get('template', 'default')
            template = self.templates.get(template_name, self.templates['default'])
            
            # Prepare template variables
            source_file = Path(document.source_path).name
            title = Path(document.source_path).stem.replace('_', ' ').replace('-', ' ').title()
            language = getattr(document, 'detected_language', config.language)
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            # Calculate duration
            if document.transcription_segments:
                duration = f"{document.transcription_segments[-1].end_time:.2f}s"
            else:
                duration = "0.00s"
            
            # Format segments
            if template_name == 'timeline':
                segments_text = self._format_timeline_segments(document.transcription_segments, config)
            else:
                segments_text = self._format_segments(document.transcription_segments, config)
            
            # Calculate statistics
            segment_count = len(document.transcription_segments)
            avg_confidence = sum(seg.confidence for seg in document.transcription_segments) / segment_count if segment_count > 0 else 0.0
            processing_time = f"{document.processing_time:.2f}s"
            
            # Format the markdown
            markdown_content = template.format(
                title=title,
                source_file=source_file,
                language=language,
                timestamp=timestamp,
                duration=duration,
                segments=segments_text,
                segment_count=segment_count,
                avg_confidence=f"{avg_confidence:.2f}",
                processing_time=processing_time,
                timeline_segments=segments_text
            )
            
            # Write to output file
            os.makedirs(os.path.dirname(document.output_path), exist_ok=True)
            with open(document.output_path, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
            
            document.status = ProcessingStatus.COMPLETED
            self.logger.info(f"Markdown formatted and saved: {document.output_path}")
            return document
            
        except Exception as e:
            document.add_error(f"Formatting failed: {str(e)}")
            return document
    
    def _format_segments(self, segments: List, config: ProcessingConfig) -> str:
        """Format transcription segments."""
        formatted_segments = []
        
        for i, segment in enumerate(segments, 1):
            segment_text = f"**{i}.** "
            
            if config.include_timestamps:
                start_time = self._format_timestamp(segment.start_time)
                end_time = self._format_timestamp(segment.end_time)
                segment_text += f"[{start_time} - {end_time}] "
            
            segment_text += segment.text
            
            if config.include_confidence:
                confidence = f"{segment.confidence:.2f}"
                segment_text += f" *(confidence: {confidence})*"
            
            formatted_segments.append(segment_text)
        
        return "\n\n".join(formatted_segments)
    
    def _format_timeline_segments(self, segments: List, config: ProcessingConfig) -> str:
        """Format segments for timeline view."""
        formatted_segments = []
        
        for segment in segments:
            start_time = self._format_timestamp(segment.start_time)
            end_time = self._format_timestamp(segment.end_time)
            
            segment_text = f"**{start_time} - {end_time}**\n{segment.text}"
            
            if config.include_confidence:
                confidence = f"{segment.confidence:.2f}"
                segment_text += f"\n*Confidence: {confidence}*"
            
            formatted_segments.append(segment_text)
        
        return "\n\n---\n\n".join(formatted_segments)
    
    def _format_timestamp(self, seconds: float) -> str:
        """Format timestamp in MM:SS format."""
        minutes = int(seconds // 60)
        seconds = int(seconds % 60)
        return f"{minutes:02d}:{seconds:02d}"
    
    def get_supported_formats(self) -> List[str]:
        """Get list of supported output formats."""
        return ['markdown', 'md']
    
    def validate_output(self, document: Document) -> bool:
        """
        Validate output document format.
        
        Args:
            document: Document to validate
            
        Returns:
            True if document output is valid
        """
        if not document.output_path:
            self.logger.error("Document has no output path")
            return False
        
        # Check if output directory is writable
        output_dir = os.path.dirname(document.output_path)
        if output_dir and not os.path.exists(output_dir):
            try:
                os.makedirs(output_dir, exist_ok=True)
            except Exception as e:
                self.logger.error(f"Cannot create output directory: {e}")
                return False
        
        # Check if output file extension is supported
        file_ext = Path(document.output_path).suffix.lower().lstrip('.')
        if file_ext not in self.get_supported_formats():
            self.logger.warning(f"Output extension '{file_ext}' not in supported formats, but proceeding")
        
        return True
    
    def get_available_templates(self) -> List[str]:
        """Get list of available templates."""
        return list(self.templates.keys())
